#!/bin/bash

set -e

swift build

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/XML/Decode
.build/debug/Tests/XML/Encode
.build/debug/Tests/XML/String
.build/debug/Tests/XML/XML
